package com.smartcampus.issuemanager.entity;

public enum IssueStatus {
    REPORTED,
    UNDERSTOOD,
    ASSIGNED,
    INVESTIGATING,
    INVESTIGATED,
    ACTION_SCHEDULED,
    ACTION_IN_PROGRESS,
    ACTION_TAKEN,
    RESOLVED_PENDING_CONFIRMATION,
    RESOLUTION_PROPOSED,
    CONFIRMED,
    CLOSED,
    WAITING_FOR_INFORMATION,
    ESCALATED,
    DUPLICATE,
    REOPENED,
    CANCELLED
}
